---
# See vagrant_1.yaml for additional shared configuration for vagrant

classes:
  - "postfix::server"
  - "procmail"
  - "ogm"
  - "dns"
  - "apache"
  - "apache::mod::rewrite"
  - "apache::mod::alias"
  - "php::cli"
  - "php::mod_php5"
  - "composer"
  - "drush"
  - "drupal"
  - "mysql"
  - "mysql::php"
  - "mysql::server"

drupal::root_user: 'vagrant'

# Install a Drupal email frontend, ogm.postfix.local
drupal::sites:
  'ogm.postfix.local':
    priority: 10
    projects:
      - og_mailinglist
      - og
      - features
      - admin_menu
      - environment_indicator
      - devel
    enable:
      - og_mailinglist
      - og
      - og_ui
      - features
      - admin_menu
      - environment_indicator
      - devel
    disable:
      - overlay
      - dashboard
      - toolbar
      - shortcut

ogm::sites:
    - domain: ogm.postfix.local
      drupal_path: "/srv/www/ogm.postfix.local/drupal"
      host: "http://ogm.postfix.local"

local_users:
  joe:
    password: password

email_aliases:
  postfix.local:
    joe.user: joe
    admin: joe
    list:
      - greg.anderson@reetstreet.com
      - greg.anderson@greenknowe.org
  virtual.local:
    test: joe
    group:
      - greg.anderson@reetstreet.com
      - greg.anderson@greenknowe.org

dns::zones:
  postfix.local:
    soa: ns1.postfix.local
    soa_email: admin@postfix.local
    nameservers:
      - "ns1"
    ip: "192.168.213.201"
    rdns: true
    a:
      client:
        data: "192.168.213.202"
        ptr: true
    mx:
      "postfix.local.":
        preference: 10
        data: "postfix.postfix.local"
  westkingdom.local:
    soa: ns1.westkingdom.local
    soa_email: admin@westkingdom.local
    nameservers:
      - "ns1"
    ip: "192.168.213.201"
    rdns: false
    mx: "postfix.postfix.local"
  mists.westkingdom.local:
    soa: ns1.mists.westkingdom.local
    soa_email: admin@westkingdom.local
    nameservers:
      - "ns1"
    ip: "192.168.213.201"
    rdns: false
    mx: "postfix.postfix.local"
  cynagua.westkingdom.local:
    soa: ns1.cynagua.westkingdom.local
    soa_email: admin@westkingdom.local
    nameservers:
      - "ns1"
    ip: "192.168.213.201"
    rdns: false
    mx: "postfix.postfix.local"
  213.168.192.IN-ADDR.ARPA:
    soa: ns1.postfix.local
    soa_email: admin@postfix.local
    nameservers:
      - "ns1"

postfix::server::db_files:
  virtual:
    content: "@postfix.local ogm"
  aliases:
    postfixdir: /etc
    content: "postmaster: vagrant"

postfix::server::myhostname: 'postfix.postfix.local'

postfix::server::mydomain: 'postfix.local'

postfix::server::mydestination: '$myhostname, localhost.$mydomain, localhost, $mydomain'

postfix::server::mailbox_command: '/usr/bin/procmail -a "$EXTENSION"'

postfix::server::inet_interfaces: 'all'

postfix::server::message_size_limit: '15360000' # 15MB

postfix::server::virtual_alias_maps:
  - hash:/etc/postfix/virtual


apache::mpm_module: prefork

php::mod_php5::inifile: /etc/php5/apache2/php.ini

php::cli::inifile: /etc/php5/cli/php.ini

mysql::server::config_hash:
  root_password: password

